{% set version = "2024.10.24" %}

package:
  name: opencl-headers
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/OpenCL-Headers/archive/v{{ version }}.zip
  sha256: d6a6462588b913cbcd91e4ddc5cd85c53dcf59099e9a2962624fcf345896ea9b

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - python *
  host:
  run:

test:
  commands:
    - if not exist %LIBRARY_INC%\\CL\\cl.h exit 1                       # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\OpenCL-Headers.pc exit 1   # [win]
    - test -f $PREFIX/include/OpenCL/cl.h                               # [osx]
    - test -f $PREFIX/include/CL/cl.h                                   # [unix]
    - test -f $PREFIX/lib/pkgconfig/OpenCL-Headers.pc                   # [unix]

about:
  home: https://www.khronos.org/registry/cl/
  dev_url: https://github.com/KhronosGroup/OpenCL-Headers
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenCL headers

extra:
  recipe-maintainers:
    - isuruf
